# Generated by Django 3.0.3 on 2020-10-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('fruits', 'fruits'), ('vegetables', 'vegetables')], default='vegetables', max_length=10),
            preserve_default=False,
        ),
    ]
