# Generated by Django 3.0.3 on 2020-10-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0003_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('value', models.IntegerField()),
                ('min_coast', models.IntegerField()),
                ('start_at', models.DateField()),
                ('finish_at', models.DateField()),
            ],
        ),
    ]
