# Generated by Django 3.0.3 on 2020-10-28 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0004_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_api.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_api.User')),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
